const courses = [
  {
    code: "INFO101",
    name: "Introduction to Information Systems",
    prereqs: "",
    spec: "no",
    link: "https://www.wgtn.ac.nz/courses/info/101/2020/offering?crn=10038",
  },
  {
    code: "INFO141",
    name: "Systems Analysis",
    prereqs: "",
    spec: "no",
    link: "https://www.wgtn.ac.nz/courses/info/141/2020/offering?crn=27093",
  },
  {
    code: "INFO151",
    name: "Databases",
    prereqs: "",
    spec: "no",
    link: "https://www.wgtn.ac.nz/courses/info/151/2020/offering?crn=27094",
  },
  {
    code: "INFO226",
    name: "Application Development",
    prereqs: "INFO151",
    spec: "it",
    link: "https://www.wgtn.ac.nz/courses/info/226/2020/offering?crn=27096",
  },
  {
    code: "INFO231",
    name: "Management of IT Projects",
    prereqs: "INFO1??",
    spec: "no",
    link: "https://www.wgtn.ac.nz/courses/info/231/2020/offering?crn=27097",
  },
  {
    code: "INFO234",
    name: "Business Process Design",
    prereqs: "INFO1??",
    spec: "ba",
    link: "https://www.wgtn.ac.nz/courses/info/234/2020/offering?crn=27098",
  },
  {
    code: "INFO246",
    name: "User Experience Design",
    prereqs: "INFO1??",
    spec: "it",
    link: "https://www.wgtn.ac.nz/courses/info/246/2020/offering?crn=27099",
  },
  {
    code: "INFO264",
    name: "Business Analytics",
    prereqs: "INFO151",
    spec: "ba",
    link: "https://www.wgtn.ac.nz/courses/info/264/2020/offering?crn=27100",
  },
  {
    code: "INFO334",
    name: "Digital Business Innovation",
    prereqs: "INFO 234",
    spec: "ba",
    link: "https://www.wgtn.ac.nz/courses/info/334/2020/offering?crn=28272",
  },
  {
    code: "INFO336",
    name: "Social Responsibility in a Digital World",
    prereqs: "INFO2??",
    spec: "no",
    link: "https://www.wgtn.ac.nz/courses/info/336/2020/offering?crn=31152",
  },
  {
    code: "INFO354",
    name: "Digital Strategy",
    prereqs: "INFO2??x2",
    spec: "no",
    link: "https://www.wgtn.ac.nz/courses/info/354/2020/offering?crn=28273",
  },
  {
    code: "INFO360",
    name: "Information Systems for Health Care",
    prereqs: "INFO2??x2",
    spec: "no",
    link: "https://www.wgtn.ac.nz/courses/info/360/2020/offering?crn=31009",
  },
  {
    code: "INFO376",
    name: "Enterprise Architecture",
    prereqs: "INFO2??x2",
    spec: "no",
    link: "https://www.wgtn.ac.nz/courses/info/376/2020/offering?crn=28274",
  },
  {
    code: "INFO377",
    name: "System Verification",
    prereqs: "INFO226",
    spec: "it",
    link: "https://www.wgtn.ac.nz/courses/info/377/2020/offering?crn=28275",
  },
  {
    code: "INFO381",
    name: "Special Topic: Advanced Web App Development",
    prereqs: "INFO226",
    spec: "no",
    link: "https://www.wgtn.ac.nz/courses/info/381/2020/offering?crn=11107",
  },
  {
    code: "INFO386",
    name: "Information Technology Architecture",
    prereqs: "INFO2??x2",
    spec: "it",
    link: "https://www.wgtn.ac.nz/courses/info/386/2020/offering?crn=28276",
  },
  {
    code: "INFO388",
    name: "Enterprise Security",
    prereqs: "INFO2??x2",
    spec: "ba",
    link: "https://www.wgtn.ac.nz/courses/info/388/2020/offering?crn=28277",
  },
  {
    code: "INFO320",
    name: "Project in Information Systems",
    prereqs: ["INFO2??x2", "INFO3??"],
    spec: "it",
    link: "https://www.wgtn.ac.nz/courses/info/320/2020/offering?crn=8597",
  },
  {
    code: "INFO395",
    name: "Case Studies in Information Systems",
    prereqs: ["INFO2??x2", "INFO3??"],
    spec: "ba",
    link: "https://www.wgtn.ac.nz/courses/info/395/2020/offering?crn=18152",
  },
];
